# Generated by Django 2.0.3 on 2018-06-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180325_1656'),
    ]

    operations = [
    ]
